colorblind_mode: True # Set True to change green color to blue

# List of topics to monitor, format is:
# topic_name Displayed name (can be multiple words) expected_frequency
# if "/" is provided at the beginning of topic_name, the topic name is considered as written, 
# if there is no "/" at the beginning, UAV_NAME is automatically added in from of the topic name (/uav1/topic_name)
want_hz: [
      "mavros/setpoint_raw/attitude Mavros 100",
      "garmin/range Garmin 100",
      "os1_cloud_node/points Ouster 10",
      # "bluefox/image_raw Bluefox 100",
      ]
