dark_mode: True
list: [
      "mavros/distance_sensor/garmin Garmin 20",
      "bluefox/image_raw Bluefox 60",
      "optic_flow/velocity OptFlow 60",
      "mavros/setpoint_raw/target_attitude Mavros setpoint attitude 100",
      ]
