dark_mode: False # Set False if you use white terminal background (intended for outdoor usage)
colorblind_mode: True # Set True to change green color to blue

# List of topics to monitor, format is:
# topic_name Displayed name (can be multiple words) expected_frequency
# if "/" is provided at the beginning of topic_name, the topic name is considered as written, 
# if there is no "/" at the beginning, UAV_NAME is automatically added in from of the topic name (/uav1/topic_name)
want_hz: [
      "garmin/range Garmin 88",
      "garmin/range_up Garmin UP 60+",
      "bluefox/image_raw Bluefox 60",
      "optic_flow/velocity OptFlow 60",
      "rplidar/scan RPLidar 20",
      "rs_d435/aligned_depth_to_color/image_raw Realsense 15",
      "orb_slam/odom OrbOdom 10",
      ]

needed_nodes: [
      "constraint_manager",
      "control_manager",
      "gain_manager",
      "mavros",
      "mavros_interface",
      "odometry",
      "nodelet_manager",
      "uav_manager",
     ]

